### ISSUE TITLE
There is no connected target issue

### ISSUE THREAD

**Issue by IvayloGeorgiev3004** [Georift/install-jellyfin-tizen#1]
Hello,
do you know why I am getting "There is no connected target." and the installation is not completed?
Thank you.

**Comment by SchoolGuy** [comment]
Same issue here. Everything else seems to be successfull-

**Comment by Georift** [comment]
Yep, I've seen this issue in two instances:

1. Once when I had an existing `sdb` connection on the TV. Try `sdb disconnect` if you have it running elsewhere.
2. When the `Host PC IP` on the screen was not set to my laptops LAN IP. Even 0.0.0.0 seemed to have issues.
![image](https://user-images.githubusercontent.com/859430/207514397-f08d8325-18d1-40b0-a748-0d2c019beb26.png)

**Comment by yelhouti** [comment]
@Georift thanks for the great repo, I am facing the same issue, even if my IP is correct. Any idea what might cause this ?

**Comment by yelhouti** [comment]
@tillcash In my case I had to to hard restart the TV (unplug replug)
