### ISSUE TITLE
Allow Setting TV Name as an Argument

### ISSUE THREAD

**Issue by tillcash** [Georift/install-jellyfin-tizen#11]
When attempting to install Jellyfin, I encountered an issue related to the TV name not being consistent between the Tizen Device Manager application and the API.

```
Attempting to connect to Samsung TV at IP address 192.168.1.68
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 192.168.1.68:26101 ...
connected to 192.168.1.68:26101
Attempting to get the TV name...
Found TV name: UA55JU6400
Attempting to install jellyfin-tizen-builds version:
https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2023-06-07
There is no UA55JU6400 target.
Total time: 00:00:00.323
```
![Capture](https://github.com/Georift/install-jellyfin-tizen/assets/19629778/f87f1770-eced-428e-8eb3-dc56e9259630)
![Capture1](https://github.com/Georift/install-jellyfin-tizen/assets/19629778/3503ac7a-24d3-48eb-83cf-96d11c771e69)

I can successfully install Jellyfin manually by using the name provided by Tizen Device Manager.

**Comment by lgnmcrules** [comment]
How did you change that to make it work?

**Comment by PCJones** [comment]
I have the same problem.

I tried changing the Samsungs TVs hostname to the target name the docker container expects but it seems like my firmware always prepends [TV] to the name.

Potential fix: Use the name property from IP:8001/api/v2/ instead of whatever API endpoint/property is being used now

**Comment by panchuz** [comment]
Any working workarround?

In my case, the correct name according to the plate on the back of the tv set is: Samsung _UN40JU6000_ Smart TV (not equal to UN40JU6100, as found by the script)

How can I use it to help the script work?

For reference purposes:
```
root@omv:~# docker run --rm georift/install-jellyfin-tizen "192.168.98.243" "Jellyfin-10.8.z"
Tag URL not provided, using latest available version: 2024-08-25-0726
You can change it by passing tag URL as third argument for this script.


        Thanks to https://github.com/jeppevinkel for providing the pre-packaged jellyfin-tizen builds!
        These builds can be found at https://github.com/jeppevinkel/jellyfin-tizen-builds

        Using Jellyfin Tizen Build Jellyfin-10.8.z.wgt
        from release: 2024-08-25-0726


Attempting to connect to Samsung TV at IP address 192.168.98.243
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to [192.168.98.243:26101](http://192.168.98.243:26101/) ...
connected to [192.168.98.243:26101](http://192.168.98.243:26101/)
Attempting to get the TV name...
Found TV name: UN40JU6100
Attempting to install jellyfin-tizen-builds Jellyfin-10.8.z.wgt from release: 2024-08-25-0726
https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/download/2024-08-25-0726/Jellyfin-10.8.z.wgt

     0K .......... .......... .......... .......... ..........  0% 3.16M 3s
    50K .......... .......... .......... .......... ..........  1% 9.35M 2s
        ======= lots of these =======
  9250K .......... .......... .......... .......... .......... 99% 14.1M 0s
  9300K .......... .......... .......... .......... .......... 99% 13.2M 0s
  9350K .......... .......... .                               100% 13.0M=0.7sThere is no UN40JU6100 target.
Total time: 00:00:00.202```

**Comment by panchuz** [comment]
Many Thanks @tillcash 
It worked.
Can´t believe a Jellyfin client released in 2024 can run on my 2015 (Tizen 2.3) tv.
Many Thanks to the author/s as well.

**Comment by AceOfError** [comment]
Thank you @tillcash, this fixed it for me as well! 

I got an error when using my TV name during the docker build, with an error complaining about uppercase letters. When I just named it "test" instead it built just fine and I got it to install on my TV. 

Another note, it would not connect unless I specified the port in the format xx.xx.xx.xx:port during the docker run.

**Comment by Georift** [comment]
I've build and deployed the latest container images. Closing this as the documentation is now correct :+1:

**Comment by nahcir** [comment]
Hey there,

sorry for reopening this one, but on Docker Hub (https://hub.docker.com/r/georift/install-jellyfin-tizen) it still says you last updated the container five months ago on May 17, 2024 at 1:09 pm. When I use the docker pull/run commands, I still end up with the same error as described by OP. Am I doing something wrong or was the container you built somehow not correctly uploaded/deployed?

Thanks in advance for looking into it!
