### ISSUE TITLE
Error: There is no connected target 

### ISSUE THREAD

**Issue by Ard3ny** [Georift/install-jellyfin-tizen#12]
Hi, I'm getting this error "There is no connected target"

`docker run --rm georift/install-jellyfin-tizen 192.168.100.170

	Thanks to https://github.com/jeppevinkel for providing the pre-packaged jellyfin-tizen builds!
	These builds can be found at https://github.com/jeppevinkel/jellyfin-tizen-builds

Attempting to connect to Samsung TV at IP address 192.168.100.170
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 192.168.100.170:26101 ...
failed to connect to 192.168.100.170:26101
Attempting to get the TV name...
Found TV name: UE50TU8072UXXH
Attempting to install jellyfin-tizen-builds version:
https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2023-09-24

     0K .......... .......... .......... .......... ..........  0% 11.8M 1s
    50K .......... .......... .......... .......... ..........  1% 14.4M 1s
   100K .......... .......... .......... .......... ..........  1% 41.9M 1s
   150K .......... .......... .......... .......... ..........  2% 56.5M 0s
   200K .......... .......... .......... .......... ..........  2% 19.7M 0s
   250K .......... .......... .......... .......... ..........  3% 85.4M 0s
   300K .......... .......... .......... .......... ..........  3% 91.6M 0s
   350K .......... .......... .......... .......... ..........  4% 88.0M 0s
   400K .......... .......... .......... .......... ..........  4%  110M 0s
   450K .......... .......... .......... .......... ..........  5% 26.0M 0s
   500K .......... .......... .......... .......... ..........  5%  144M 0s
   550K .......... .......... .......... .......... ..........  6%  127M 0s
   600K .......... .......... .......... .......... ..........  6% 98.5M 0s
   650K .......... .......... .......... .......... ..........  7%  103M 0s
   700K .......... .......... .......... .......... ..........  8%  157M 0s
   750K .......... .......... .......... .......... ..........  8%  122M 0s
   800K .......... .......... .......... .......... ..........  9% 89.4M 0s
   850K .......... .......... .......... .......... ..........  9%  115M 0s
   900K .......... .......... .......... .......... .......... 10%  120M 0s
   950K .......... .......... .......... .......... .......... 10% 93.5M 0s
  1000K .......... .......... .......... .......... .......... 11% 93.0M 0s
  1050K .......... .......... .......... .......... .......... 11% 67.0M 0s
  1100K .......... .......... .......... .......... .......... 12% 85.4M 0s
  1150K .......... .......... .......... .......... .......... 12% 88.1M 0s
  1200K .......... .......... .......... .......... .......... 13%  142M 0s
  1250K .......... .......... .......... .......... .......... 13%  125M 0s
  1300K .......... .......... .......... .......... .......... 14%  109M 0s
  1350K .......... .......... .......... .......... .......... 14% 98.1M 0s
  1400K .......... .......... .......... .......... .......... 15% 89.7M 0s
  1450K .......... .......... .......... .......... .......... 16%  138M 0s
  1500K .......... .......... .......... .......... .......... 16%  135M 0s
  1550K .......... .......... .......... .......... .......... 17%  103M 0s
  1600K .......... .......... .......... .......... .......... 17% 93.0M 0s
  1650K .......... .......... .......... .......... .......... 18%  130M 0s
  1700K .......... .......... .......... .......... .......... 18%  135M 0s
  1750K .......... .......... .......... .......... .......... 19% 95.9M 0s
  1800K .......... .......... .......... .......... .......... 19% 92.5M 0s
  1850K .......... .......... .......... .......... .......... 20%  108M 0s
  1900K .......... .......... .......... .......... .......... 20%  117M 0s
  1950K .......... .......... .......... .......... .......... 21% 96.2M 0s
  2000K .......... .......... .......... .......... .......... 21%  140M 0s
  2050K .......... .......... .......... .......... .......... 22%  121M 0s
  2100K .......... .......... .......... .......... .......... 22%  113M 0s
  2150K .......... .......... .......... .......... .......... 23% 93.3M 0s
  2200K .......... .......... .......... .......... .......... 24% 90.4M 0s
  2250K .......... .......... .......... .......... .......... 24%  174M 0s
  2300K .......... .......... .......... .......... .......... 25%  117M 0s
  2350K .......... .......... .......... .......... .......... 25%  106M 0s
  2400K .......... .......... .......... .......... .......... 26% 96.5M 0s
  2450K .......... .......... .......... .......... .......... 26%  162M 0s
  2500K .......... .......... .......... .......... .......... 27%  120M 0s
  2550K .......... .......... .......... .......... .......... 27% 98.6M 0s
  2600K .......... .......... .......... .......... .......... 28% 97.0M 0s
  2650K .......... .......... .......... .......... .......... 28% 99.6M 0s
  2700K .......... .......... .......... .......... .......... 29%  120M 0s
  2750K .......... .......... .......... .......... .......... 29%  159M 0s
  2800K .......... .......... .......... .......... .......... 30%  103M 0s
  2850K .......... .......... .......... .......... .......... 30% 99.4M 0s
  2900K .......... .......... .......... .......... .......... 31%  111M 0s
  2950K .......... .......... .......... .......... .......... 32%  186M 0s
  3000K .......... .......... .......... .......... .......... 32% 80.8M 0s
  3050K .......... .......... .......... .......... .......... 33%  112M 0s
  3100K .......... .......... .......... .......... .......... 33% 94.7M 0s
  3150K .......... .......... .......... .......... .......... 34%  165M 0s
  3200K .......... .......... .......... .......... .......... 34%  114M 0s
  3250K .......... .......... .......... .......... .......... 35%  101M 0s
  3300K .......... .......... .......... .......... .......... 35% 97.4M 0s
  3350K .......... .......... .......... .......... .......... 36%  171M 0s
  3400K .......... .......... .......... .......... .......... 36% 94.0M 0s
  3450K .......... .......... .......... .......... .......... 37%  112M 0s
  3500K .......... .......... .......... .......... .......... 37%  107M 0s
  3550K .......... .......... .......... .......... .......... 38% 97.2M 0s
  3600K .......... .......... .......... .......... .......... 38%  143M 0s
  3650K .......... .......... .......... .......... .......... 39%  118M 0s
  3700K .......... .......... .......... .......... .......... 40%  100M 0s
  3750K .......... .......... .......... .......... .......... 40%  131M 0s
  3800K .......... .......... .......... .......... .......... 41% 89.5M 0s
  3850K .......... .......... .......... .......... .......... 41%  127M 0s
  3900K .......... .......... .......... .......... .......... 42%  113M 0s
  3950K .......... .......... .......... .......... .......... 42%  118M 0s
  4000K .......... .......... .......... .......... .......... 43% 93.4M 0s
  4050K .......... .......... .......... .......... .......... 43%  136M 0s
  4100K .......... .......... .......... .......... .......... 44%  982K 0s
  4150K .......... .......... .......... .......... .......... 44%  144M 0s
  4200K .......... .......... .......... .......... .......... 45%  125M 0s
  4250K .......... .......... .......... .......... .......... 45%  289M 0s
  4300K .......... .......... .......... .......... .......... 46%  326M 0s
  4350K .......... .......... .......... .......... .......... 46%  183M 0s
  4400K .......... .......... .......... .......... .......... 47%  233M 0s
  4450K .......... .......... .......... .......... .......... 48%  161M 0s
  4500K .......... .......... .......... .......... .......... 48% 87.6M 0s
  4550K .......... .......... .......... .......... .......... 49%  128M 0s
  4600K .......... .......... .......... .......... .......... 49%  145M 0s
  4650K .......... .......... .......... .......... .......... 50% 97.3M 0s
  4700K .......... .......... .......... .......... .......... 50%  118M 0s
  4750K .......... .......... .......... .......... .......... 51% 86.9M 0s
  4800K .......... .......... .......... .......... .......... 51%  157M 0s
  4850K .......... .......... .......... .......... .......... 52% 19.4M 0s
  4900K .......... .......... .......... .......... .......... 52% 95.9M 0s
  4950K .......... .......... .......... .......... .......... 53% 93.6M 0s
  5000K .......... .......... .......... .......... .......... 53%  136M 0s
  5050K .......... .......... .......... .......... .......... 54% 81.9M 0s
  5100K .......... .......... .......... .......... .......... 54%  218M 0s
  5150K .......... .......... .......... .......... .......... 55%  128M 0s
  5200K .......... .......... .......... .......... .......... 56%  104M 0s
  5250K .......... .......... .......... .......... .......... 56%  115M 0s
  5300K .......... .......... .......... .......... .......... 57%  115M 0s
  5350K .......... .......... .......... .......... .......... 57%  104M 0s
  5400K .......... .......... .......... .......... .......... 58% 87.5M 0s
  5450K .......... .......... .......... .......... .......... 58%  173M 0s
  5500K .......... .......... .......... .......... .......... 59% 95.8M 0s
  5550K .......... .......... .......... .......... .......... 59%  157M 0s
  5600K .......... .......... .......... .......... .......... 60% 75.2M 0s
  5650K .......... .......... .......... .......... .......... 60%  144M 0s
  5700K .......... .......... .......... .......... .......... 61% 79.6M 0s
  5750K .......... .......... .......... .......... .......... 61%  180M 0s
  5800K .......... .......... .......... .......... .......... 62%  116M 0s
  5850K .......... .......... .......... .......... .......... 62%  126M 0s
  5900K .......... .......... .......... .......... .......... 63%  126M 0s
  5950K .......... .......... .......... .......... .......... 64% 95.7M 0s
  6000K .......... .......... .......... .......... .......... 64% 94.7M 0s
  6050K .......... .......... .......... .......... .......... 65%  118M 0s
  6100K .......... .......... .......... .......... .......... 65%  122M 0s
  6150K .......... .......... .......... .......... .......... 66%  138M 0s
  6200K .......... .......... .......... .......... .......... 66% 79.1M 0s
  6250K .......... .......... .......... .......... .......... 67%  157M 0s
  6300K .......... .......... .......... .......... .......... 67%  149M 0s
  6350K .......... .......... .......... .......... .......... 68% 86.7M 0s
  6400K .......... .......... .......... .......... .......... 68%  122M 0s
  6450K .......... .......... .......... .......... .......... 69%  105M 0s
  6500K .......... .......... .......... .......... .......... 69% 94.2M 0s
  6550K .......... .......... .......... .......... .......... 70% 96.7M 0s
  6600K .......... .......... .......... .......... .......... 70%  222M 0s
  6650K .......... .......... .......... .......... .......... 71% 61.1M 0s
  6700K .......... .......... .......... .......... .......... 72%  270M 0s
  6750K .......... .......... .......... .......... .......... 72%  108M 0s
  6800K .......... .......... .......... .......... .......... 73%  130M 0s
  6850K .......... .......... .......... .......... .......... 73%  109M 0s
  6900K .......... .......... .......... .......... .......... 74% 87.8M 0s
  6950K .......... .......... .......... .......... .......... 74%  126M 0s
  7000K .......... .......... .......... .......... .......... 75%  136M 0s
  7050K .......... .......... .......... .......... .......... 75%  111M 0s
  7100K .......... .......... .......... .......... .......... 76%  120M 0s
  7150K .......... .......... .......... .......... .......... 76% 96.0M 0s
  7200K .......... .......... .......... .......... .......... 77%  111M 0s
  7250K .......... .......... .......... .......... .......... 77%  108M 0s
  7300K .......... .......... .......... .......... .......... 78%  123M 0s
  7350K .......... .......... .......... .......... .......... 78%  107M 0s
  7400K .......... .......... .......... .......... .......... 79%  116M 0s
  7450K .......... .......... .......... .......... .......... 80%  140M 0s
  7500K .......... .......... .......... .......... .......... 80% 87.4M 0s
  7550K .......... .......... .......... .......... .......... 81%  119M 0s
  7600K .......... .......... .......... .......... .......... 81% 89.8M 0s
  7650K .......... .......... .......... .......... .......... 82%  176M 0s
  7700K .......... .......... .......... .......... .......... 82%  109M 0s
  7750K .......... .......... .......... .......... .......... 83% 96.7M 0s
  7800K .......... .......... .......... .......... .......... 83%  136M 0s
  7850K .......... .......... .......... .......... .......... 84% 95.0M 0s
  7900K .......... .......... .......... .......... .......... 84%  121M 0s
  7950K .......... .......... .......... .......... .......... 85%  115M 0s
  8000K .......... .......... .......... .......... .......... 85%  145M 0s
  8050K .......... .......... .......... .......... .......... 86% 87.1M 0s
  8100K .......... .......... .......... .......... .......... 86%  122M 0s
  8150K .......... .......... .......... .......... .......... 87%  109M 0s
  8200K .......... .......... .......... .......... .......... 88%  173M 0s
  8250K .......... .......... .......... .......... .......... 88%  812K 0s
  8300K .......... .......... .......... .......... .......... 89%  121M 0s
  8350K .......... .......... .......... .......... .......... 89% 98.5M 0s
  8400K .......... .......... .......... .......... .......... 90% 94.3M 0s
  8450K .......... .......... .......... .......... .......... 90%  124M 0s
  8500K .......... .......... .......... .......... .......... 91% 84.7M 0s
  8550K .......... .......... .......... .......... .......... 91%  138M 0s
  8600K .......... .......... .......... .......... .......... 92% 93.2M 0s
  8650K .......... .......... .......... .......... .......... 92%  129M 0s
  8700K .......... .......... .......... .......... .......... 93% 89.2M 0s
  8750K .......... .......... .......... .......... .......... 93%  119M 0s
  8800K .......... .......... .......... .......... .......... 94% 82.5M 0s
  8850K .......... .......... .......... .......... .......... 94%  179M 0s
  8900K .......... .......... .......... .......... .......... 95%  119M 0s
  8950K .......... .......... .......... .......... .......... 96%  138M 0s
  9000K .......... .......... .......... .......... .......... 96% 91.1M 0s
  9050K .......... .......... .......... .......... .......... 97%  131M 0s
  9100K .......... .......... .......... .......... .......... 97% 87.8M 0s
  9150K .......... .......... .......... .......... .......... 98%  117M 0s
  9200K .......... .......... .......... .......... .......... 98%  130M 0s
  9250K .......... .......... .......... .......... .......... 99%  105M 0s
  9300K .......... .......... .......... .......... .......... 99%  110M 0s
  9350K .......... .......... .                               100%  373M=0.2sThere is no connected target.
Total time: 00:00:00.075`

**Comment by Georift** [comment]
Thanks for the report, there are a few issues similar to this. I'm not exactly sure why we're able to get the TV name but SDB is having issues connecting to the TV.

I'll take a look when I have some time.

**Comment by Georift** [comment]
In the mean time, I've heard some reports that folks have had success rebooting their TV. Pressing and holding the power button until it turns off entirely. When starting again it should show a QLED or Samsung logo for a lot longer than normal.

**Comment by Ard3ny** [comment]
Yea, I tried that. I was trying other methods as well and none of them were working, so I realized there must be something wrong with my setup. After a few hours of googling around, I've found the solution.

In the TV apps setting, where you activate the DEVELOPER MODE with (12345), there is also an IP address you can fill out. 
I thought that It defaults to dynamic and this option was only if I want to have it static, but I was wrong.

I had to manually enter the IP of my PC which I was executing the connection from (tizen studio) . 

I don't know that if it's such a banality nobody is mentioning it or just my TV is weird, but that fixed it for me.

**Comment by Georift** [comment]
Thanks for reporting back. I have noticed that too, in my TV it defaulted it `0.0.0.0` as a placeholder, which I assumed was "allow any IP address".

I'll try catch this case and add a note suggesting that people add their IP address.

**Comment by AndreWohnsland** [comment]
Thanks for this. I couldn't get it working until I specified the exact IP, also thought that it would allow all.

**Comment by Sylk** [comment]
How can I access the IP config settings for this in the older Samsung TV's such as the ones from 2013?

**Comment by Marcosaurios** [comment]
Worked like a charm. Same here, needed to introduce the host's IP to connect properly

**Comment by Kev1n121** [comment]
Didnt work for me Still the same error

**Comment by azcn2503** [comment]
For me, I had the IPs set correctly, and had to run the following command:

```
docker run -it --ulimit nofile=122880:122880 -m 3G --rm georift/install-jellyfin-tizen 192.168.86.60
```

But it refused to work until I powered the TV off physically and turned it back on again.
