### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by S7ewie** [Georift/install-jellyfin-tizen#16]
I've followed the instructions to the best of my ability. When I run the command in step 2 I get:

```
Attempting to connect to Samsung TV at IP address 192.168.20.10
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 192.168.20.10:26101 ...
failed to connect to 192.168.20.10:26101
Attempting to get the TV name...
Found TV name: QE55S90CATXXU
Attempting to install jellyfin-tizen-builds version:
https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2023-11-29
```

Then it runs all the way through to 100% but finishes with:

`There is no connected target.`

It seems to have failed to connect for some reason, though it is able to get the the TV name.

**Comment by TheQuantumPhysicist** [comment]
I solved this problem by putting the IP address of the source machine. This can be done at the same place where you enable developer mode. I believe this is a security option so that not anyone can connect to the TV and install crap on it.

**Comment by skyw33** [comment]
I have the same issue and I have already indicated the source IP address.

**Comment by S7ewie** [comment]
Yeah I had the correct IP. I could connect to the TV in Tizen Studio with no issues.

I ran the command in [/jeppevinkel/jellyfin-tizen-builds](https://github.com/jeppevinkel/jellyfin-tizen-builds) and it worked so I'm not really sure why this one wasn't working

**Comment by Georift** [comment]
@skyw33 @S7ewie you might find hard rebooting your TV may help the problem.

**Comment by dawsmac** [comment]
Just an FYI if running from Kubernetes 

kubectl run  jellyfin --restart=Never --rm -i --tty  --image  georift/install-jellyfin-tizen  <TIZEN_IP>, 

Works but like others have said make sure you put in your host IP of the machine running docker or K8 into the tv.

**Comment by bishumoharana** [comment]
Strangely enough after restart of TV, the connection on Tizen Device manager got disconnected and with that disconnected status I executed the command 
And Wolah! it works

**Comment by zorrograndeepee** [comment]
I tried everything and still, the message at the end "There is no connected target." what can I do ?

**Comment by AdventureSMBW** [comment]
Having the same problem. However, I cant enter the Host PC IP on my Samsung TV. In the developer mode window, the Host PC IP is 0.0.0.0 and cannot be changed. Nothing happens when I click it. Tried getting in and out of dev mode and hard rebooting. How can I enter that IP address?

**Comment by DavidWittman** [comment]
> Having the same problem. However, I cant enter the Host PC IP on my Samsung TV. In the developer mode window, the Host PC IP is 0.0.0.0 and cannot be changed. Nothing happens when I click it. Tried getting in and out of dev mode and hard rebooting. How can I enter that IP address?

You need to enter the IP address using the "123" button on the remote just like you did to enable Developer mode.

**Comment by AdventureSMBW** [comment]
> You need to enter the IP address using the "123" button on the remote just like you did to enable Developer mode.

You literally just solved my weeklong problem. Jellyfin is installed. THANK YOU!!!!!

**Comment by tahasalim** [comment]
Solved it!

You MUST set the Host IP and press OK, then leave the TV.

If you're still having the issue, you can verify the connection by doing the following:
Install Tizen Studio Device Manager and connect to the TV. Then actively disconnect from the TV in the device manager (since you've verified the connection) and try running the script again.

Voila!

**Comment by Toupycat** [comment]
> Solved it!
> 
> You MUST set the Host IP and press OK, then leave the TV.
> 
> If you're still having the issue, you can verify the connection by doing the following: Install Tizen Studio Device Manager and connect to the TV. Then actively disconnect from the TV in the device manager (since you've verified the connection) and try running the script again.
> 
> Voila!

THANKS!
Tried everything while the host and target IPs were correctly set. Turns out you have to UNCHECK the connection in Device Manager for it to be able to find the device in the terminal. Which doesn't sounds right, but this is the way!

**Comment by rras3k** [comment]
Mistake I made. I put the TV in dev mode and entered the IP of my PC, then I turned off the TV and turned it back on. The problem is that my PC's IP address is not saved when the TV is turned off. 
So you have to do it in 2 times.
1) Put the TV in dev mode.
2) Turn off the TV and turn it back on
3) Enter the PC address
4) Send Docker command.
It worked very well for me.

**Comment by JakubKopys** [comment]
> > Solved it!
> > You MUST set the Host IP and press OK, then leave the TV.
> > If you're still having the issue, you can verify the connection by doing the following: Install Tizen Studio Device Manager and connect to the TV. Then actively disconnect from the TV in the device manager (since you've verified the connection) and try running the script again.
> > Voila!
> 
> THANKS! Tried everything while the host and target IPs were correctly set. Turns out I had Device Manager running and connected to the tv while trying to run the script. You really have to UNCHECK the connection in Device Manager for it to be able to find the device in the terminal.

Same! For some reason, the connection has to be unchecked in the Device Manager before you run the script. I did that and it worked well.

**Comment by Georift** [comment]
Looks like we have proper solutions here so I'll close this for now. Feel free to open another if things crop up.

**Comment by Lyqed** [comment]
For anyone having issues, and you're tv is in right-to-left language — you need to type in the ip of the computer you are trying to connect from _backwards_. I.e if your pc IP is 192.168.1.2, type 2.1.168.192

yeah.... I'm truly dumbfounded by this behavior.

**Comment by h-nazzal** [comment]
> For anyone having issues, and you're tv is in right-to-left language — you need to type in the ip of the computer you are trying to connect from _backwards_. I.e if your pc IP is 192.168.1.2, type 2.1.168.192
> 
> yeah.... I'm truly dumbfounded by this behavior.

dude you saved the day...
literally 4 days of hair pulling

thanks

**Comment by MaroufAlsubaie** [comment]
> For anyone having issues, and you're tv is in right-to-left language — you need to type in the ip of the computer you are trying to connect from _backwards_. I.e if your pc IP is 192.168.1.2, type 2.1.168.192
> 
> yeah.... I'm truly dumbfounded by this behavior.

thank you.

i almost brake my TV

**Comment by etainad008** [comment]
> For anyone having issues, and you're tv is in right-to-left language — you need to type in the ip of the computer you are trying to connect from _backwards_. I.e if your pc IP is 192.168.1.2, type 2.1.168.192
> 
> yeah.... I'm truly dumbfounded by this behavior.

You are the GOAT!
