### ISSUE TITLE
Dowload Failed

### ISSUE THREAD

**Issue by Aquila210** [Georift/install-jellyfin-tizen#18]
Connects to the TV fine and downloads the package fine, but I get the following error when it tries to install:
install wgt
```
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt
was_install_app return WAS_TRUE
app_id[wgt] install start
app_id[wgt] download failed[116]
spend time for wascmd is [13]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:06.718
```
Got the same error when I tried the original method with Tizen Studio

**Comment by TimRadder** [comment]
I am also encountering this issue with the same output at the end. Everything downloads fine, but it fals in the end

**Comment by Georift** [comment]
I believe `download failed[116]` means that there is [no space left on your TV](https://github.com/jellyfin/jellyfin-tizen/issues/10#issuecomment-612719339).

Could you please confirm in the Apps section of the TV how much free space is left on the device?

**Comment by TimRadder** [comment]
> I believe `download failed[116]` means that there is [no space left on your TV](https://github.com/jellyfin/jellyfin-tizen/issues/10#issuecomment-612719339).
> 
> Could you please confirm in the Apps section of the TV how much free space is left on the device?

I have 134MB of free space remaining. How much is required for Jellyfin to install?

**Comment by mayjs** [comment]
@TimRadder I just ran into the same issue.
After uninstalling some of the bloatware apps I got to about 100MB of free space (according to the app manager), which was enough to install. Now I'm at about 35MB left.

Not sure why 134MB is not enough in your case.

**Comment by Georift** [comment]
Still having this issue @Aquila210? Any resolution. If so perhaps we can close this?

**Comment by Georift** [comment]
Closing because this has gotten stale.
