### ISSUE TITLE
Add "long press home" as alternative to the "123" button

### ISSUE THREAD

**Issue by dedors** [Georift/install-jellyfin-tizen#19]
It worked flawlessly to install jellyfin on my Samsung M8 Monitor.

Only thing I had to figure out is how to get into developer mode. The monitor comes with a white remote with no numbers or "123", and the linked Samsung page didn't mention anything too. Long pressing home button did the trick, it's like a hidden "123" button.

Maybe a little hint in the howto can help others too. 

![24881](https://github.com/Georift/install-jellyfin-tizen/assets/17786985/674b1830-29c0-48d2-a1c5-1c8d1820cfe5)

**Comment by Georift** [comment]
Oh thanks for the report, I'll look to add a note about your situation thanks 👍

**Comment by uberhalit** [comment]
Much easier to connect a regular USB keyboard instead.

**Comment by ash-development** [comment]
on my TU700D tv, holding the Home button starts the Remote Management prompt (warning: very loud). this might just be the case with remotes with no numbers
