### ISSUE TITLE
TV Can not connect to server

### ISSUE THREAD

**Issue by dlongnecker2** [Georift/install-jellyfin-tizen#2]
Thanks for this package.    Got it installed on my Samsung (one trick was I had to enter 1 2 3 4 5 to get into developer mode fast!)

MY Mac pushed the package well:

Attempting to connect to Samsung TV at IP address 192.168.2.144
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 192.168.2.144:26101 ...
connected to 192.168.2.144:26101
Attempting to get the TV name...
Found TV name: QN75Q8BAAFXZA
Attempting to install jellyfin-tizen-builds version:
https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2022-12-05
.
.
.
spend time for wascmd is [9808]ms
Installed the package: Id(AprZAARz4r.Jellyfin)
Tizen application is successfully installed.
Total time: 00:00:17.620

When I start jellyfish on my Samsung, it says "No servers have been found using the automatic discovery".

SO I enter the ip of 192.168.2.131:8096 and it repeats itself.   I enter 192.168.2.1.131:8096 on a computer on my wifi network and it gets to the jellyfish server without a problem....so the server is running fine.   No firewalls or anything else like that on my wifi network.

Suggestions/thoughts?
Dennis

**Comment by Georift** [comment]
Hmm, so you're seeing this error on the installed Jellyfin Tizen app? If that's the case I think the installler has worked correctly your best bet would be to raise an issue with https://github.com/jellyfin/jellyfin-tizen.

Glad the installer worked well for you!

**Comment by dlongnecker2** [comment]
This was my user error.    I didn’t realize when entering server up I have to select okay.   I was clicking continue first without okaying the IP.   Onceci did that I am good.  

Love the build.   No more plex for me.    Thanks for creating the Samsung build!!!!

**Comment by Georift** [comment]
No worries at all, glad it helped. I only did the slightly bit at the end to package it up. The links in the readme are the folks who have done most of the hard work.

**Comment by Chocodu31** [comment]
Hey Sorry for intervening, i got the same problem and i don't understand how you fix that__

**Comment by Chocodu31** [comment]
Ok nevermind i'm stupid
