### ISSUE TITLE
Docker issue resolving IPv6

### ISSUE THREAD

**Issue by KnobFaces** [Georift/install-jellyfin-tizen#20]
I'm running in a non-IPV6 network, and trying to install following instructions leaves me with:

Unable to find image 'georift/install-jellyfin-tizen:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp [2600:1f18:2148:bc02:445d:9ace:d20b:c303]:443: connect: cannot assign requested address.

I've tried to forcefully disable IPV6, not sure why its actually present as the host adapter doesn't have IPV6 at all

Any suggestions?

**Comment by Georift** [comment]
Because this is happening while pulling a container image, I think it's best to report this to the docker project itself.

Feel free to reopen if you don't think this is the case.
