### ISSUE TITLE
How to install other app build?

### ISSUE THREAD

**Issue by hossihub** [Georift/install-jellyfin-tizen#23]
Can I install the other prebuilt versions using this?

**Comment by Georift** [comment]
This doesn't support it natively. How would you want to provide the other built versions?

Is it local to your filesystem? Perhaps other HTTP links?

**Comment by bleach1520** [comment]
I need previous version of jellyfin client

**Comment by leekslk** [comment]
@Georift thanks for the convenient way for installing jellyfin on tizen. Been using this for a while and it has been running great. I was assuming that this was built off https://github.com/jellyfin/jellyfin-tizen. Does that mean that re-installing the client updates it to the latest version (possibly v10.9+)? (sorry to hijack the comments)

**Comment by hossihub** [comment]
> This doesn't support it currently. How would you want to provide the other built versions?
> 
> Is it local to your filesystem? Perhaps other HTTP links?

Hmm would it be possible to add parameter with the https link to the wgt package ?

**Comment by hossihub** [comment]
> This doesn't support it currently. How would you want to provide the other built versions?
> 
> Is it local to your filesystem? Perhaps other HTTP links?

Hmm would it be possible to add parameter with the https link to the wgt package ?

**Comment by Georift** [comment]
@bleach1520 that definitely makes sense, supporting earlier versions is a great improvement.

Also @hossihub I agree. Open to adding direct manual link specification to 👍

**Comment by Georift** [comment]
@pgodzwa just added a change to let you do this. Checkout the README for more instructions.
