### ISSUE TITLE
Could not download from host computer over wifi, had to use wired LAN

### ISSUE THREAD

**Issue by elapse2039** [Georift/install-jellyfin-tizen#3]
Networking is always a fun topic to troubleshoot... but I found that I had to have the TV and host computer had to be on same wired LAN segment.  It didnt work for me over wifi despite the script finding the Samsung TV. The debugger connection failed until I was on a wired LAN.  I found a hint from on a Samsung [support thread](https://forum.developer.samsung.com/t/developer-mode-ip-address/8646/7).

The second issue that delayed me trying LAN was that I also constantly saw on my 2016 Samsung TV (v1310 firmware) that the host IP address disappear everytime I went into developer modal popup. It wasn't clear if the IP address should remain visible and I spent a lot of time re-entering and rebooting the TV just in case.

It would be helpful to include a bit more info in documentation on what success looks like and perhaps a hint on trying ethernet LAN.  It was hard to know if I had network issues or the TV actually was in Developer Mode listening to the right Host computer IP address.  I had no 'success' logs to compare to what I was seeing and oddly, the failure log found the TV model but also said it failed to connect ("There is no connected target").  It still went ahead and started the download, presumably to nowhere.

My network:
- Wifi 2Ghz Ubiquiti AP
- Layer2 Switch to Samsung UN55MU8000 TV.

Host Computers
- MacBook Pro over wifi
- Lenovo Laptop on Layer2 Switch

The Lenovo laptop successfully connected and downloaded the jellyfin app to the TV.  I am not aware of anything on Wifi network that is different to LAN in terms of firewalls, filtering.  I dont know if the developer SDK has any networking requirements (eg: UDP, multicast etc?).  

Attached are success and failure logs.

[jellfin-download-samsung-tizen-success.txt](https://github.com/Georift/install-jellyfin-tizen/files/10435618/jellfin-download-samsung-tizen-success.txt)

[jellyfin-download-samsung-tizen-failure.txt](https://github.com/Georift/install-jellyfin-tizen/files/10435619/jellyfin-download-samsung-tizen-failure.txt)

**Comment by Georift** [comment]
Thanks for the detailed description of what happened.

Strange that the `sdb connect IP` command fails, but you're script is still able to fetch the TV's name using a HTTP request to that same IP address.

Certainly feels like perhaps this is a Host IP issue on the TV? Perhaps `sdb` is requiring developer mode but the HTTP request is happy without it.

This looks exactly the same as the issue over at #1. Where the TV name was detected, so I think you're right, it's definitely some issues with the host IP not being set correctly.

I'll have a look this evening and see if I can add a conditional to detect this and guide the user through the install.

**Comment by yelhouti** [comment]
I tried using both wired and wifi no luck.
I watched someone video and saw that when they renter the screen for enable the dev mode, the IP was still visible.
In my case the IP fields are empty. Can anyone confirm that they can see the IP when they enter back (after leaving the menu and entering 12345 again or restart and entering 12345)?

**Comment by yelhouti** [comment]
EDIT: Key for me was to: Unplug and Plug the TV as explained here: https://developer.samsung.com/smarttv/develop/extension-libraries/smart-view-sdk/receiver-apps/debugging.html

**Comment by Georift** [comment]
@yelhouti 

> Can anyone confirm that they can see the IP when they enter back

Yep when I enter back into the developer menu I see the IP address listed there. This is even after a full restart of the TV.

**Comment by yelhouti** [comment]
@Georift thanks for answering, for the next person, as I mentioned I can't see the IP, maybe your firmware has the same bug. But unplug, plug works.

**Comment by PCJones** [comment]
I had the exact same problem, unplugging fixed it for me too! Thanks @yelhouti

**Comment by AndreaDiNapoli** [comment]
Hi, I'm having the exact same problem (TV name is found, but get the "there is no connected target", but I wasn't able to solve it by rebooting/unplugging the TV.

Any suggestion?

**Comment by ankitsinghaniyaz** [comment]
Facing the same problem, by TV seems to not have any free space available lol.

**Comment by uberhalit** [comment]
So I ran into this issue today after successfully installing the app on another TV on the same network previously. Turns out I had a typo in host IP in developer menu. Fixed the IP and issue went away immediately.

**Comment by Georift** [comment]
Closing this for now as this seems a little stale. If it comes up again feel free to open another issue.
