### ISSUE TITLE
Install fail - missing package

### ISSUE THREAD

**Issue by Sonusss** [Georift/install-jellyfin-tizen#31]
I tried with the following command for the latest release:
`docker run --rm georift/install-jellyfin-tizen 10.10.0.53 Jellyfin-TrueHD "https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-05-31-0728"`

But it report tat there is no package named Jellyfin-TrueHD.wgt while it is well present at:
https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-05-31-0728

Here is the full output:
```
docker run --rm georift/install-jellyfin-tizen 10.10.0.53 Jellyfin-TrueHD "https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-05-31-0728"


	Thanks to https://github.com/jeppevinkel for providing the pre-packaged jellyfin-tizen builds!
	These builds can be found at https://github.com/jeppevinkel/jellyfin-tizen-builds

	Using Jellyfin Tizen Build Jellyfin-TrueHD.wgt
	from release: 2024-05-31-0728


Attempting to connect to Samsung TV at IP address 10.10.0.53
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 10.10.0.53:26101 ...
connected to 10.10.0.53:26101
Attempting to get the TV name...
Found TV name: QE55QN85AATXXN
Attempting to install jellyfin-tizen-builds Jellyfin-TrueHD.wgt from release: 2024-05-31-0728
https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/download/2024-05-31-0728/Jellyfin-TrueHD.wgt
There is no package with named Jellyfin-TrueHD.wgt.
[Fail] Fail install. There is the problem about package.
Total time: 00:00:00.209

```

**Comment by pgodzwa** [comment]
Unfortunately I cannot reproduce it - using the same command on my side finished successfully. I have also tried with latest version available (https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-06-01-2328) and it also works for me.

**Comment by Georift** [comment]
cheers for the investigation @pgodzwa. Glad you got it sorted @Sonusss
