### ISSUE TITLE
I need a more detailes installation guide

### ISSUE THREAD

**Issue by twinko** [Georift/install-jellyfin-tizen#33]
Hello,

i never touched docker and im really struggeling to follow this repo installtion guide.
Can anybody elaborate, what software do i need and give detailed information how to execute the mentioned code?

Running windows 11, developermode with hostz IP is setup.

Thank you in advance :)

**Comment by ash-development** [comment]
you should really just need [docker](https://www.docker.com/products/docker-desktop/) and make sure it is running properly (virtualization enabled, etc). after that just run the command in cmd prompt and it should be good to go!

**Comment by twinko** [comment]
@ash-development 
hey thanks this already helped. I'll try to reinstall the app in teh next few weeks to try it. Maybe we could add the link and your short describtion to the Readme?

**Comment by Georift** [comment]
@ash-development improved the instructions, so I'm closing this. @twinko if you're still having trouble feel free to re-open.
