### ISSUE TITLE
Can't navigate in the app

### ISSUE THREAD

**Issue by bugline** [Georift/install-jellyfin-tizen#36]
I installed the app without any issues. Then, I launched it, and everything worked fine for connecting to the server until I entered the server. Once on the homepage, I can't do anything except use the return button and quit the app. The directional buttons do nothing (although they work fine on the connection page).

TV : QU55QN85B
Server version : 10.9.9

**Comment by Georift** [comment]
Best to open this issue with the upstream [jellyfin-web](https://github.com/jellyfin/jellyfin-web)

**Comment by oriaj3** [comment]
Were you able to fix it? The same thing happens to me and I can't find anything in the official github.

**Comment by bugline** [comment]
The problem came from my server, but in the interface on TV nothing told me that the server was the problem. It was when I test jellyfin on another device and it did'nt work as well that I looked to the server log. I put the jellyfin cache in /dev/shm/Jellyfin but this folder is in ram so only temporary so when my computer restart I can't access to the folder which no more exist and made impossible to play any film. After put cache in /dev/shm all work perfectly. So you should test to another device if it work and check server log.
