### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by Lyqed** [Georift/install-jellyfin-tizen#41]
Hi all, im getting the failed to connect issue despite trying everything suggested in the issue "Failed to connect #16".

- i tried both the docker command and connecting from the tizen device manager. both get a field to connect. I have no firewall in my home router and the packets _are_ reaching the tv on that port (verified with telnet). I am really clueless as to what to check nest.
- needless to say ive double checked and triple checked the host pc ip and the tv ip ip I use.
- also tried running the command directly (last image)
- my tv model: s90c

![image](https://github.com/user-attachments/assets/11694f26-9331-4e1f-9dd3-6c2e72e34884)
![image](https://github.com/user-attachments/assets/5205dd8d-0276-4207-b07e-badd695a9973)
![image](https://github.com/user-attachments/assets/0586c072-e194-4b5a-9d3d-d9136a80a195)
![image](https://github.com/user-attachments/assets/7786d0e6-1b88-4060-a47d-50ec9705c64d)

**Comment by Lyqed** [comment]
For anyone having issues, and you're tv is in right-to-left language — you need to type in the ip of the computer you are trying to connect from _backwards_. I.e if your pc IP is 192.168.1.2, type 2.1.168.192

yeah.... I'm truly dumbfounded by this behavior. 

gonna close this issue now.

**Comment by Georift** [comment]
Thanks for the issue, yeah that's a really weird one. I've added some documentation as requested [here](https://github.com/Georift/install-jellyfin-tizen/issues/30)
