### ISSUE TITLE
cant install on S90c

### ISSUE THREAD

**Issue by Fjox** [Georift/install-jellyfin-tizen#43]
ive tried multiple times and it just doesnt work. i even tried the example  command and it didnt work

**Comment by Fjox** [comment]
turn out it was a dns issue but even after fixing it it just didnt work

**Comment by Georift** [comment]
Can you paste your error log here? What are you seeing?

**Comment by Fjox** [comment]
this is obviusly some issue with the S90c since it can be installed fine on a TU7079

**Comment by Fjox** [comment]
it was some issue with the linux install i used last time... #linuxjank
