### ISSUE TITLE
Unable to find image 'ghcr.io/georift/install-jellyfin-tizen:latest' locally

### ISSUE THREAD

**Issue by kbekkering** [Georift/install-jellyfin-tizen#45]
When running `docker run --rm ghcr.io/georift/install-jellyfin-tizen 192.168.1.133 Jellyfin-TrueHD "https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-05-13-0139"` on my Mac it fails with the following error:

`Unable to find image 'ghcr.io/georift/install-jellyfin-tizen:latest' locally`

The same error occurs when using `docker run --rm ghcr.io/georift/install-jellyfin-tizen 192.168.1.133`

Should there be a different set of commands for Mac? Virtualization is enabled, so I'm at a loss.

**Comment by kbekkering** [comment]
issue not resolved, but desired result has been achieved by alternative method namely installing a build from https://github.com/jeppevinkel/jellyfin-tizen-builds.

**Comment by Georift** [comment]
Apologies @kbekkering, I suspect this was as a result of it being an ARM based mac? I will give it a try soon and see if I can get an ARM container image going.
