### ISSUE TITLE
Hyphens in the TV name cause the install to crash

### ISSUE THREAD

**Issue by chartspots** [Georift/install-jellyfin-tizen#47]
Below the output. Seems to find the projector and connect, but app does not become available. Any idea on how to solve?

Build option not provided, using default one: Jellyfin
You can change it by passing option name as second argument for this script.
Tag URL not provided, using latest available version: 2024-10-28-1739
You can change it by passing tag URL as third argument for this script.

        Thanks to https://github.com/jeppevinkel for providing the pre-packaged jellyfin-tizen builds!
        These builds can be found at https://github.com/jeppevinkel/jellyfin-tizen-builds

        Using Jellyfin Tizen Build Jellyfin.wgt
        from release: 2024-10-28-1739

Attempting to connect to Samsung TV at IP address 192.168.50.27
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 192.168.50.27:26101 ...
connected to 192.168.50.27:26101
Attempting to get the TV name...
Found TV name: SP
Attempting to install jellyfin-tizen-builds Jellyfin.wgt from release: 2024-10-28-1739
https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/download/2024-10-28-1739/Jellyfin.wgt

     0K .......... .......... .......... .......... ..........  0% 2.77M 4s
    50K .......... .......... .......... .......... ..........  0% 7.40M 3s
   100K .......... .......... .......... .......... ..........  1% 3.86M 3s
   150K .......... .......... .......... .......... ..........  1% 18.7M 2s
   200K .......... .......... .......... .......... ..........  2% 7.13M 2s
   250K .......... .......... .......... .......... ..........  2% 8.14M 2s
   300K .......... .......... .......... .......... ..........  3% 8.88M 2s
   350K .......... .......... .......... .......... ..........  3% 9.59M 2s
   400K .......... .......... .......... .......... ..........  4% 13.1M 2s
   450K .......... .......... .......... .......... ..........  4% 11.7M 1s
   500K .......... .......... .......... .......... ..........  5% 8.89M 1s
   550K .......... .......... .......... .......... ..........  5% 16.4M 1s
   600K .......... .......... .......... .......... ..........  6% 8.98M 1s
   650K .......... .......... .......... .......... ..........  6% 12.4M 1s
   700K .......... .......... .......... .......... ..........  7% 1.29M 2s
   750K .......... .......... .......... .......... ..........  7% 34.2M 2s
   800K .......... .......... .......... .......... ..........  7% 2.50M 2s
   850K .......... .......... .......... .......... ..........  8% 31.7M 2s
   900K .......... .......... .......... .......... ..........  8% 27.9M 2s
   950K .......... .......... .......... .......... ..........  9% 28.9M 1s
  1000K .......... .......... .......... .......... ..........  9% 38.8M 1s
  1050K .......... .......... .......... .......... .......... 10% 36.5M 1s
  1100K .......... .......... .......... .......... .......... 10% 27.9M 1s
  1150K .......... .......... .......... .......... .......... 11% 37.2M 1s
  1200K .......... .......... .......... .......... .......... 11% 39.4M 1s
  1250K .......... .......... .......... .......... .......... 12% 36.3M 1s
  1300K .......... .......... .......... .......... .......... 12% 37.5M 1s
  1350K .......... .......... .......... .......... .......... 13% 14.0M 1s
  1400K .......... .......... .......... .......... .......... 13% 10.1M 1s
  1450K .......... .......... .......... .......... .......... 14% 14.7M 1s
  1500K .......... .......... .......... .......... .......... 14% 1.13M 1s
  1550K .......... .......... .......... .......... .......... 14% 1.72M 1s
  1600K .......... .......... .......... .......... .......... 15% 40.9M 1s
  1650K .......... .......... .......... .......... .......... 15% 37.3M 1s
  1700K .......... .......... .......... .......... .......... 16% 39.6M 1s
  1750K .......... .......... .......... .......... .......... 16% 42.4M 1s
  1800K .......... .......... .......... .......... .......... 17% 37.0M 1s
  1850K .......... .......... .......... .......... .......... 17% 39.2M 1s
  1900K .......... .......... .......... .......... .......... 18% 38.8M 1s
  1950K .......... .......... .......... .......... .......... 18% 35.4M 1s
  2000K .......... .......... .......... .......... .......... 19% 44.0M 1s
  2050K .......... .......... .......... .......... .......... 19% 36.8M 1s
  2100K .......... .......... .......... .......... .......... 20% 43.6M 1s
  2150K .......... .......... .......... .......... .......... 20% 40.0M 1s
  2200K .......... .......... .......... .......... .......... 21% 43.2M 1s
  2250K .......... .......... .......... .......... .......... 21% 39.9M 1s
  2300K .......... .......... .......... .......... .......... 21% 34.7M 1s
  2350K .......... .......... .......... .......... .......... 22% 39.7M 1s
  2400K .......... .......... .......... .......... .......... 22% 40.7M 1s
  2450K .......... .......... .......... .......... .......... 23% 39.8M 1s
  2500K .......... .......... .......... .......... .......... 23% 49.3M 1s
  2550K .......... .......... .......... .......... .......... 24% 21.7M 1s
  2600K .......... .......... .......... .......... .......... 24% 8.76M 1s
  2650K .......... .......... .......... .......... .......... 25% 12.2M 1s
  2700K .......... .......... .......... .......... .......... 25% 8.91M 1s
  2750K .......... .......... .......... .......... .......... 26% 13.2M 1s
  2800K .......... .......... .......... .......... .......... 26% 8.51M 1s
  2850K .......... .......... .......... .......... .......... 27% 14.3M 1s
  2900K .......... .......... .......... .......... .......... 27% 15.3M 1s
  2950K .......... .......... .......... .......... .......... 28% 8.93M 1s
  3000K .......... .......... .......... .......... .......... 28% 9.42M 1s
  3050K .......... .......... .......... .......... .......... 28% 13.1M 1s
  3100K .......... .......... .......... .......... .......... 29% 8.80M 1s
  3150K .......... .......... .......... .......... .......... 29% 9.61M 1s
  3200K .......... .......... .......... .......... .......... 30% 13.9M 1s
  3250K .......... .......... .......... .......... .......... 30% 13.5M 1s
  3300K .......... .......... .......... .......... .......... 31% 11.5M 1s
  3350K .......... .......... .......... .......... .......... 31% 12.4M 1s
  3400K .......... .......... .......... .......... .......... 32% 7.91M 1s
  3450K .......... .......... .......... .......... .......... 32% 12.9M 1s
  3500K .......... .......... .......... .......... .......... 33% 7.76M 1s
  3550K .......... .......... .......... .......... .......... 33% 17.8M 1s
  3600K .......... .......... .......... .......... .......... 34% 11.5M 1s
  3650K .......... .......... .......... .......... .......... 34% 10.6M 1s
  3700K .......... .......... .......... .......... .......... 35% 9.45M 1s
  3750K .......... .......... .......... .......... .......... 35% 14.2M 1s
  3800K .......... .......... .......... .......... .......... 35% 8.41M 1s
  3850K .......... .......... .......... .......... .......... 36% 10.7M 1s
  3900K .......... .......... .......... .......... .......... 36% 12.6M 1s
  3950K .......... .......... .......... .......... .......... 37% 10.4M 1s
  4000K .......... .......... .......... .......... .......... 37% 14.0M 1s
  4050K .......... .......... .......... .......... .......... 38% 10.9M 1s
  4100K .......... .......... .......... .......... .......... 38% 11.8M 1s
  4150K .......... .......... .......... .......... .......... 39% 8.76M 1s
  4200K .......... .......... .......... .......... .......... 39% 7.02M 1s
  4250K .......... .......... .......... .......... .......... 40% 20.1M 1s
  4300K .......... .......... .......... .......... .......... 40% 10.8M 1s
  4350K .......... .......... .......... .......... .......... 41% 13.0M 1s
  4400K .......... .......... .......... .......... .......... 41% 11.3M 1s
  4450K .......... .......... .......... .......... .......... 42% 11.8M 1s
  4500K .......... .......... .......... .......... .......... 42% 10.9M 1s
  4550K .......... .......... .......... .......... .......... 42% 10.1M 1s
  4600K .......... .......... .......... .......... .......... 43% 8.43M 1s
  4650K .......... .......... .......... .......... .......... 43% 12.7M 1s
  4700K .......... .......... .......... .......... .......... 44% 9.38M 1s
  4750K .......... .......... .......... .......... .......... 44% 15.8M 1s
  4800K .......... .......... .......... .......... .......... 45% 13.3M 1s
  4850K .......... .......... .......... .......... .......... 45% 7.87M 1s
  4900K .......... .......... .......... .......... .......... 46% 10.9M 1s
  4950K .......... .......... .......... .......... .......... 46% 14.8M 1s
  5000K .......... .......... .......... .......... .......... 47% 9.46M 1s
  5050K .......... .......... .......... .......... .......... 47% 11.9M 1s
  5100K .......... .......... .......... .......... .......... 48% 8.66M 1s
  5150K .......... .......... .......... .......... .......... 48% 13.9M 1s
  5200K .......... .......... .......... .......... .......... 49% 10.7M 1s
  5250K .......... .......... .......... .......... .......... 49% 11.8M 1s
  5300K .......... .......... .......... .......... .......... 49% 10.0M 1s
  5350K .......... .......... .......... .......... .......... 50% 13.8M 1s
  5400K .......... .......... .......... .......... .......... 50% 8.07M 1s
  5450K .......... .......... .......... .......... .......... 51% 10.7M 1s
  5500K .......... .......... .......... .......... .......... 51% 11.3M 0s
  5550K .......... .......... .......... .......... .......... 52% 12.4M 0s
  5600K .......... .......... .......... .......... .......... 52% 10.5M 0s
  5650K .......... .......... .......... .......... .......... 53% 9.76M 0s
  5700K .......... .......... .......... .......... .......... 53% 14.0M 0s
  5750K .......... .......... .......... .......... .......... 54% 12.0M 0s
  5800K .......... .......... .......... .......... .......... 54% 7.85M 0s
  5850K .......... .......... .......... .......... .......... 55% 10.7M 0s
  5900K .......... .......... .......... .......... .......... 55% 15.8M 0s
  5950K .......... .......... .......... .......... .......... 56% 6.28M 0s
  6000K .......... .......... .......... .......... .......... 56% 28.3M 0s
  6050K .......... .......... .......... .......... .......... 56% 14.9M 0s
  6100K .......... .......... .......... .......... .......... 57% 9.95M 0s
  6150K .......... .......... .......... .......... .......... 57% 8.61M 0s
  6200K .......... .......... .......... .......... .......... 58% 10.7M 0s
  6250K .......... .......... .......... .......... .......... 58% 11.6M 0s
  6300K .......... .......... .......... .......... .......... 59% 14.1M 0s
  6350K .......... .......... .......... .......... .......... 59% 9.57M 0s
  6400K .......... .......... .......... .......... .......... 60% 12.3M 0s
  6450K .......... .......... .......... .......... .......... 60% 11.4M 0s
  6500K .......... .......... .......... .......... .......... 61% 11.7M 0s
  6550K .......... .......... .......... .......... .......... 61% 8.35M 0s
  6600K .......... .......... .......... .......... .......... 62% 9.60M 0s
  6650K .......... .......... .......... .......... .......... 62% 11.0M 0s
  6700K .......... .......... .......... .......... .......... 63% 10.9M 0s
  6750K .......... .......... .......... .......... .......... 63% 13.3M 0s
  6800K .......... .......... .......... .......... .......... 63% 12.1M 0s
  6850K .......... .......... .......... .......... .......... 64% 10.8M 0s
  6900K .......... .......... .......... .......... .......... 64% 12.0M 0s
  6950K .......... .......... .......... .......... .......... 65% 9.86M 0s
  7000K .......... .......... .......... .......... .......... 65% 10.6M 0s
  7050K .......... .......... .......... .......... .......... 66% 8.50M 0s
  7100K .......... .......... .......... .......... .......... 66% 15.4M 0s
  7150K .......... .......... .......... .......... .......... 67% 9.82M 0s
  7200K .......... .......... .......... .......... .......... 67% 12.2M 0s
  7250K .......... .......... .......... .......... .......... 68% 9.64M 0s
  7300K .......... .......... .......... .......... .......... 68% 12.9M 0s
  7350K .......... .......... .......... .......... .......... 69% 12.3M 0s
  7400K .......... .......... .......... .......... .......... 69% 8.86M 0s
  7450K .......... .......... .......... .......... .......... 70% 11.4M 0s
  7500K .......... .......... .......... .......... .......... 70% 10.2M 0s
  7550K .......... .......... .......... .......... .......... 70% 9.75M 0s
  7600K .......... .......... .......... .......... .......... 71% 14.9M 0s
  7650K .......... .......... .......... .......... .......... 71% 9.43M 0s
  7700K .......... .......... .......... .......... .......... 72% 14.4M 0s
  7750K .......... .......... .......... .......... .......... 72% 10.2M 0s
  7800K .......... .......... .......... .......... .......... 73% 9.27M 0s
  7850K .......... .......... .......... .......... .......... 73% 11.5M 0s
  7900K .......... .......... .......... .......... .......... 74% 12.4M 0s
  7950K .......... .......... .......... .......... .......... 74% 9.45M 0s
  8000K .......... .......... .......... .......... .......... 75% 12.7M 0s
  8050K .......... .......... .......... .......... .......... 75% 9.50M 0s
  8100K .......... .......... .......... .......... .......... 76% 14.5M 0s
  8150K .......... .......... .......... .......... .......... 76% 9.47M 0s
  8200K .......... .......... .......... .......... .......... 77% 11.1M 0s
  8250K .......... .......... .......... .......... .......... 77% 9.27M 0s
  8300K .......... .......... .......... .......... .......... 77% 11.6M 0s
  8350K .......... .......... .......... .......... .......... 78% 13.2M 0s
  8400K .......... .......... .......... .......... .......... 78% 12.0M 0s
  8450K .......... .......... .......... .......... .......... 79% 9.61M 0s
  8500K .......... .......... .......... .......... .......... 79% 12.1M 0s
  8550K .......... .......... .......... .......... .......... 80% 11.2M 0s
  8600K .......... .......... .......... .......... .......... 80% 7.93M 0s
  8650K .......... .......... .......... .......... .......... 81% 11.3M 0s
  8700K .......... .......... .......... .......... .......... 81% 10.0M 0s
  8750K .......... .......... .......... .......... .......... 82% 18.6M 0s
  8800K .......... .......... .......... .......... .......... 82% 9.24M 0s
  8850K .......... .......... .......... .......... .......... 83% 13.4M 0s
  8900K .......... .......... .......... .......... .......... 83% 10.4M 0s
  8950K .......... .......... .......... .......... .......... 84% 13.8M 0s
  9000K .......... .......... .......... .......... .......... 84% 6.85M 0s
  9050K .......... .......... .......... .......... .......... 85% 12.7M 0s
  9100K .......... .......... .......... .......... .......... 85% 10.8M 0s
  9150K .......... .......... .......... .......... .......... 85% 14.9M 0s
  9200K .......... .......... .......... .......... .......... 86% 9.28M 0s
  9250K .......... .......... .......... .......... .......... 86% 11.6M 0s
  9300K .......... .......... .......... .......... .......... 87% 12.1M 0s
  9350K .......... .......... .......... .......... .......... 87% 11.9M 0s
  9400K .......... .......... .......... .......... .......... 88% 7.34M 0s
  9450K .......... .......... .......... .......... .......... 88% 12.6M 0s
  9500K .......... .......... .......... .......... .......... 89% 10.6M 0s
  9550K .......... .......... .......... .......... .......... 89% 12.2M 0s
  9600K .......... .......... .......... .......... .......... 90% 8.85M 0s
  9650K .......... .......... .......... .......... .......... 90% 23.1M 0s
  9700K .......... .......... .......... .......... .......... 91% 10.6M 0s
  9750K .......... .......... .......... .......... .......... 91% 12.2M 0s
  9800K .......... .......... .......... .......... .......... 92% 7.17M 0s
  9850K .......... .......... .......... .......... .......... 92% 13.7M 0s
  9900K .......... .......... .......... .......... .......... 92% 10.7M 0s
  9950K .......... .......... .......... .......... .......... 93% 10.8M 0s
 10000K .......... .......... .......... .......... .......... 93% 7.61M 0s
 10050K .......... .......... .......... .......... .......... 94% 1.63M 0s
 10100K .......... .......... .......... .......... .......... 94% 40.0M 0s
 10150K .......... .......... .......... .......... .......... 95% 38.7M 0s
 10200K .......... .......... .......... .......... .......... 95% 34.4M 0s
 10250K .......... .......... .......... .......... .......... 96% 39.5M 0s
 10300K .......... .......... .......... .......... .......... 96% 34.9M 0s
 10350K .......... .......... .......... .......... .......... 97% 43.8M 0s
 10400K .......... .......... .......... .......... .......... 97% 42.5M 0s
 10450K .......... .......... .......... .......... .......... 98% 39.9M 0s
 10500K .......... .......... .......... .......... .......... 98% 21.9M 0s
 10550K .......... .......... .......... .......... .......... 99% 6.88M 0s
 10600K .......... .......... .......... .......... .......... 99% 15.1M 0s
 10650K .......... .......... .......... .......... .......... 99% 17.1M 0s
 10700K .....                                                 100%  121M=1.0sThere is no SP target.
Total time: 00:00:00.316

**Comment by chartspots** [comment]
The issue seems to be that the Projector name is "SP-LSP3BLAXXE". It contains a "-" which causes the script to fail. 

I was able to install the app via the regular way (using tizen studio), using this command: tizen.bat install -n Jellyfin.wgt -t "SP-LSP3BLAXXE"      Procedure from here: https://github.com/jeppevinkel/jellyfin-tizen-builds

**Comment by Freakstyleer** [comment]
I am running into a similar issue:

PS C:\Users\Nils> docker run --rm georift/install-jellyfin-tizen 192.168.188.36
Build option not provided, using default one: Jellyfin
You can change it by passing option name as second argument for this script.
Tag URL not provided, using latest available version: 2024-10-28-1739
You can change it by passing tag URL as third argument for this script.


        Thanks to https://github.com/jeppevinkel for providing the pre-packaged jellyfin-tizen builds!
        These builds can be found at https://github.com/jeppevinkel/jellyfin-tizen-builds

        Using Jellyfin Tizen Build Jellyfin.wgt
        from release: 2024-10-28-1739


Attempting to connect to Samsung TV at IP address 192.168.188.36
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
error: failed to connect to remote target '192.168.188.36'
Attempting to get the TV name...
Found TV name: UE55KU6079
Attempting to install jellyfin-tizen-builds Jellyfin.wgt from release: 2024-10-28-1739
https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/download/2024-10-28-1739/Jellyfin.wgt

     0K .......... .......... .......... .......... ..........  0% 1.53M 7s
    50K .......... .......... .......... .......... ..........  0% 7.89M 4s
   100K .......... .......... .......... .......... ..........  1% 11.4M 3s
   150K .......... .......... .......... .......... ..........  1% 10.9M 2s
   200K .......... .......... .......... .......... ..........  2% 7.93M 2s
   250K .......... .......... .......... .......... ..........  2% 7.06M 2s
   300K .......... .......... .......... .......... ..........  3% 9.01M 2s
   350K .......... .......... .......... .......... ..........  3% 13.8M 2s
   400K .......... .......... .......... .......... ..........  4% 14.9M 2s
   450K .......... .......... .......... .......... ..........  4% 23.1M 2s
   500K .......... .......... .......... .......... ..........  5% 18.3M 1s
   550K .......... .......... .......... .......... ..........  5% 13.9M 1s
   600K .......... .......... .......... .......... ..........  6% 21.4M 1s
   650K .......... .......... .......... .......... ..........  6% 12.1M 1s
   700K .......... .......... .......... .......... ..........  7% 19.5M 1s
   750K .......... .......... .......... .......... ..........  7% 3.40M 1s
   800K .......... .......... .......... .......... ..........  7% 21.9M 1s
   850K .......... .......... .......... .......... ..........  8% 25.6M 1s
   900K .......... .......... .......... .......... ..........  8% 23.0M 1s
   950K .......... .......... .......... .......... ..........  9% 38.5M 1s
  1000K .......... .......... .......... .......... ..........  9% 23.1M 1s
  1050K .......... .......... .......... .......... .......... 10% 12.9M 1s
  1100K .......... .......... .......... .......... .......... 10% 16.8M 1s
  1150K .......... .......... .......... .......... .......... 11% 18.4M 1s
  1200K .......... .......... .......... .......... .......... 11% 16.8M 1s
  1250K .......... .......... .......... .......... .......... 12% 20.1M 1s
  1300K .......... .......... .......... .......... .......... 12% 15.1M 1s
  1350K .......... .......... .......... .......... .......... 13% 19.2M 1s
  1400K .......... .......... .......... .......... .......... 13% 18.3M 1s
  1450K .......... .......... .......... .......... .......... 14% 20.7M 1s
  1500K .......... .......... .......... .......... .......... 14% 13.1M 1s
  1550K .......... .......... .......... .......... .......... 14% 17.1M 1s
  1600K .......... .......... .......... .......... .......... 15% 18.7M 1s
  1650K .......... .......... .......... .......... .......... 15% 19.1M 1s
  1700K .......... .......... .......... .......... .......... 16% 16.5M 1s
  1750K .......... .......... .......... .......... .......... 16% 17.6M 1s
  1800K .......... .......... .......... .......... .......... 17% 16.1M 1s
  1850K .......... .......... .......... .......... .......... 17% 17.7M 1s
  1900K .......... .......... .......... .......... .......... 18% 8.81M 1s
  1950K .......... .......... .......... .......... .......... 18% 15.2M 1s
  2000K .......... .......... .......... .......... .......... 19% 19.0M 1s
  2050K .......... .......... .......... .......... .......... 19% 19.4M 1s
  2100K .......... .......... .......... .......... .......... 20% 14.8M 1s
  2150K .......... .......... .......... .......... .......... 20% 15.8M 1s
  2200K .......... .......... .......... .......... .......... 21% 15.4M 1s
  2250K .......... .......... .......... .......... .......... 21% 10.8M 1s
  2300K .......... .......... .......... .......... .......... 21% 12.0M 1s
  2350K .......... .......... .......... .......... .......... 22% 16.2M 1s
  2400K .......... .......... .......... .......... .......... 22% 13.5M 1s
  2450K .......... .......... .......... .......... .......... 23% 15.8M 1s
  2500K .......... .......... .......... .......... .......... 23% 15.3M 1s
  2550K .......... .......... .......... .......... .......... 24% 20.7M 1s
  2600K .......... .......... .......... .......... .......... 24% 20.1M 1s
  2650K .......... .......... .......... .......... .......... 25% 19.0M 1s
  2700K .......... .......... .......... .......... .......... 25% 14.4M 1s
  2750K .......... .......... .......... .......... .......... 26% 15.9M 1s
  2800K .......... .......... .......... .......... .......... 26% 18.0M 1s
  2850K .......... .......... .......... .......... .......... 27% 32.9M 1s
  2900K .......... .......... .......... .......... .......... 27% 17.9M 1s
  2950K .......... .......... .......... .......... .......... 28% 20.7M 1s
  3000K .......... .......... .......... .......... .......... 28% 13.7M 1s
  3050K .......... .......... .......... .......... .......... 28% 28.2M 1s
  3100K .......... .......... .......... .......... .......... 29% 15.0M 1s
  3150K .......... .......... .......... .......... .......... 29% 22.2M 1s
  3200K .......... .......... .......... .......... .......... 30% 22.4M 1s
  3250K .......... .......... .......... .......... .......... 30% 20.5M 1s
  3300K .......... .......... .......... .......... .......... 31% 17.7M 1s
  3350K .......... .......... .......... .......... .......... 31% 21.5M 1s
  3400K .......... .......... .......... .......... .......... 32% 23.6M 1s
  3450K .......... .......... .......... .......... .......... 32% 26.3M 1s
  3500K .......... .......... .......... .......... .......... 33% 20.4M 1s
  3550K .......... .......... .......... .......... .......... 33% 22.6M 1s
  3600K .......... .......... .......... .......... .......... 34% 24.8M 1s
  3650K .......... .......... .......... .......... .......... 34% 19.3M 0s
  3700K .......... .......... .......... .......... .......... 35% 18.3M 0s
  3750K .......... .......... .......... .......... .......... 35% 26.4M 0s
  3800K .......... .......... .......... .......... .......... 35% 29.0M 0s
  3850K .......... .......... .......... .......... .......... 36% 23.4M 0s
  3900K .......... .......... .......... .......... .......... 36% 16.6M 0s
  3950K .......... .......... .......... .......... .......... 37% 21.3M 0s
  4000K .......... .......... .......... .......... .......... 37% 24.0M 0s
  4050K .......... .......... .......... .......... .......... 38% 21.7M 0s
  4100K .......... .......... .......... .......... .......... 38% 22.9M 0s
  4150K .......... .......... .......... .......... .......... 39% 27.1M 0s
  4200K .......... .......... .......... .......... .......... 39% 25.2M 0s
  4250K .......... .......... .......... .......... .......... 40% 28.4M 0s
  4300K .......... .......... .......... .......... .......... 40% 19.9M 0s
  4350K .......... .......... .......... .......... .......... 41% 23.9M 0s
  4400K .......... .......... .......... .......... .......... 41% 25.0M 0s
  4450K .......... .......... .......... .......... .......... 42% 22.5M 0s
  4500K .......... .......... .......... .......... .......... 42% 23.1M 0s
  4550K .......... .......... .......... .......... .......... 42% 23.2M 0s
  4600K .......... .......... .......... .......... .......... 43% 25.2M 0s
  4650K .......... .......... .......... .......... .......... 43% 28.5M 0s
  4700K .......... .......... .......... .......... .......... 44% 17.9M 0s
  4750K .......... .......... .......... .......... .......... 44% 21.1M 0s
  4800K .......... .......... .......... .......... .......... 45% 21.1M 0s
  4850K .......... .......... .......... .......... .......... 45% 22.1M 0s
  4900K .......... .......... .......... .......... .......... 46% 22.6M 0s
  4950K .......... .......... .......... .......... .......... 46% 22.5M 0s
  5000K .......... .......... .......... .......... .......... 47% 18.1M 0s
  5050K .......... .......... .......... .......... .......... 47% 27.6M 0s
  5100K .......... .......... .......... .......... .......... 48% 15.2M 0s
  5150K .......... .......... .......... .......... .......... 48% 23.1M 0s
  5200K .......... .......... .......... .......... .......... 49% 27.2M 0s
  5250K .......... .......... .......... .......... .......... 49% 20.6M 0s
  5300K .......... .......... .......... .......... .......... 49% 23.1M 0s
  5350K .......... .......... .......... .......... .......... 50% 22.6M 0s
  5400K .......... .......... .......... .......... .......... 50% 25.6M 0s
  5450K .......... .......... .......... .......... .......... 51% 22.3M 0s
  5500K .......... .......... .......... .......... .......... 51% 17.3M 0s
  5550K .......... .......... .......... .......... .......... 52% 20.3M 0s
  5600K .......... .......... .......... .......... .......... 52% 20.9M 0s
  5650K .......... .......... .......... .......... .......... 53% 25.7M 0s
  5700K .......... .......... .......... .......... .......... 53% 21.7M 0s
  5750K .......... .......... .......... .......... .......... 54% 24.8M 0s
  5800K .......... .......... .......... .......... .......... 54% 27.7M 0s
  5850K .......... .......... .......... .......... .......... 55% 20.6M 0s
  5900K .......... .......... .......... .......... .......... 55% 24.5M 0s
  5950K .......... .......... .......... .......... .......... 56% 20.5M 0s
  6000K .......... .......... .......... .......... .......... 56% 28.4M 0s
  6050K .......... .......... .......... .......... .......... 56% 22.9M 0s
  6100K .......... .......... .......... .......... .......... 57% 21.6M 0s
  6150K .......... .......... .......... .......... .......... 57% 31.6M 0s
  6200K .......... .......... .......... .......... .......... 58% 20.6M 0s
  6250K .......... .......... .......... .......... .......... 58% 25.1M 0s
  6300K .......... .......... .......... .......... .......... 59% 21.3M 0s
  6350K .......... .......... .......... .......... .......... 59% 19.6M 0s
  6400K .......... .......... .......... .......... .......... 60% 26.1M 0s
  6450K .......... .......... .......... .......... .......... 60% 23.0M 0s
  6500K .......... .......... .......... .......... .......... 61% 22.4M 0s
  6550K .......... .......... .......... .......... .......... 61% 23.7M 0s
  6600K .......... .......... .......... .......... .......... 62% 26.2M 0s
  6650K .......... .......... .......... .......... .......... 62% 22.9M 0s
  6700K .......... .......... .......... .......... .......... 63% 20.9M 0s
  6750K .......... .......... .......... .......... .......... 63% 19.6M 0s
  6800K .......... .......... .......... .......... .......... 63% 28.5M 0s
  6850K .......... .......... .......... .......... .......... 64% 23.5M 0s
  6900K .......... .......... .......... .......... .......... 64% 16.2M 0s
  6950K .......... .......... .......... .......... .......... 65% 29.6M 0s
  7000K .......... .......... .......... .......... .......... 65% 20.4M 0s
  7050K .......... .......... .......... .......... .......... 66% 35.3M 0s
  7100K .......... .......... .......... .......... .......... 66% 14.9M 0s
  7150K .......... .......... .......... .......... .......... 67% 28.0M 0s
  7200K .......... .......... .......... .......... .......... 67% 12.7M 0s
  7250K .......... .......... .......... .......... .......... 68%  229M 0s
  7300K .......... .......... .......... .......... .......... 68% 29.8M 0s
  7350K .......... .......... .......... .......... .......... 69%  194M 0s
  7400K .......... .......... .......... .......... .......... 69% 32.8M 0s
  7450K .......... .......... .......... .......... .......... 70% 20.5M 0s
  7500K .......... .......... .......... .......... .......... 70% 26.3M 0s
  7550K .......... .......... .......... .......... .......... 70% 22.0M 0s
  7600K .......... .......... .......... .......... .......... 71% 23.0M 0s
  7650K .......... .......... .......... .......... .......... 71% 26.8M 0s
  7700K .......... .......... .......... .......... .......... 72% 24.6M 0s
  7750K .......... .......... .......... .......... .......... 72% 26.6M 0s
  7800K .......... .......... .......... .......... .......... 73% 22.2M 0s
  7850K .......... .......... .......... .......... .......... 73% 32.2M 0s
  7900K .......... .......... .......... .......... .......... 74% 17.1M 0s
  7950K .......... .......... .......... .......... .......... 74% 21.7M 0s
  8000K .......... .......... .......... .......... .......... 75% 18.2M 0s
  8050K .......... .......... .......... .......... .......... 75% 23.8M 0s
  8100K .......... .......... .......... .......... .......... 76% 24.4M 0s
  8150K .......... .......... .......... .......... .......... 76% 26.7M 0s
  8200K .......... .......... .......... .......... .......... 77% 22.4M 0s
  8250K .......... .......... .......... .......... .......... 77% 23.8M 0s
  8300K .......... .......... .......... .......... .......... 77% 17.0M 0s
  8350K .......... .......... .......... .......... .......... 78% 27.9M 0s
  8400K .......... .......... .......... .......... .......... 78% 19.2M 0s
  8450K .......... .......... .......... .......... .......... 79% 22.1M 0s
  8500K .......... .......... .......... .......... .......... 79% 25.0M 0s
  8550K .......... .......... .......... .......... .......... 80% 21.1M 0s
  8600K .......... .......... .......... .......... .......... 80% 36.4M 0s
  8650K .......... .......... .......... .......... .......... 81% 25.9M 0s
  8700K .......... .......... .......... .......... .......... 81% 22.7M 0s
  8750K .......... .......... .......... .......... .......... 82% 20.7M 0s
  8800K .......... .......... .......... .......... .......... 82% 23.4M 0s
  8850K .......... .......... .......... .......... .......... 83% 18.8M 0s
  8900K .......... .......... .......... .......... .......... 83% 23.9M 0s
  8950K .......... .......... .......... .......... .......... 84% 25.6M 0s
  9000K .......... .......... .......... .......... .......... 84% 24.4M 0s
  9050K .......... .......... .......... .......... .......... 85% 22.5M 0s
  9100K .......... .......... .......... .......... .......... 85% 22.0M 0s
  9150K .......... .......... .......... .......... .......... 85% 18.8M 0s
  9200K .......... .......... .......... .......... .......... 86% 30.3M 0s
  9250K .......... .......... .......... .......... .......... 86% 24.0M 0s
  9300K .......... .......... .......... .......... .......... 87% 26.6M 0s
  9350K .......... .......... .......... .......... .......... 87% 23.3M 0s
  9400K .......... .......... .......... .......... .......... 88% 33.8M 0s
  9450K .......... .......... .......... .......... .......... 88% 27.5M 0s
  9500K .......... .......... .......... .......... .......... 89% 18.7M 0s
  9550K .......... .......... .......... .......... .......... 89% 19.6M 0s
  9600K .......... .......... .......... .......... .......... 90% 23.9M 0s
  9650K .......... .......... .......... .......... .......... 90% 26.0M 0s
  9700K .......... .......... .......... .......... .......... 91% 25.0M 0s
  9750K .......... .......... .......... .......... .......... 91% 23.9M 0s
  9800K .......... .......... .......... .......... .......... 92% 23.4M 0s
  9850K .......... .......... .......... .......... .......... 92% 25.2M 0s
  9900K .......... .......... .......... .......... .......... 92% 19.6M 0s
  9950K .......... .......... .......... .......... .......... 93% 37.6M 0s
 10000K .......... .......... .......... .......... .......... 93% 17.4M 0s
 10050K .......... .......... .......... .......... .......... 94% 27.6M 0s
 10100K .......... .......... .......... .......... .......... 94% 23.5M 0s
 10150K .......... .......... .......... .......... .......... 95% 25.5M 0s
 10200K .......... .......... .......... .......... .......... 95% 26.6M 0s
 10250K .......... .......... .......... .......... .......... 96% 24.8M 0s
 10300K .......... .......... .......... .......... .......... 96% 25.1M 0s
 10350K .......... .......... .......... .......... .......... 97% 18.9M 0s
 10400K .......... .......... .......... .......... .......... 97% 22.8M 0s
 10450K .......... .......... .......... .......... .......... 98% 27.8M 0s
 10500K .......... .......... .......... .......... .......... 98% 28.3M 0s
 10550K .......... .......... .......... .......... .......... 99% 22.4M 0s
 10600K .......... .......... .......... .......... .......... 99% 26.4M 0s
 10650K .......... .......... .......... .......... .......... 99% 23.9M 0s
 10700K .....                                                 100% 66.1M=0.6sThere is no connected target.
Total time: 00:00:00.117

**Comment by Georift** [comment]
Thank you for the report, we're already quoting the TV name, we're already quoting the TV name in the final command like you shared.

I wonder if this command is somehow causing trouble:
```
TV_NAME=$(sdb devices | grep -E 'device\s+\w+' -o | sed 's/device//' - | xargs)
```

**Comment by domenicoblanco** [comment]
I think that's the case, in my experience there weren't hyphens.
@chartspots could you try editing the script replacing `device\s+\w+` with `device\s+\S+\s+\w+`?

**Comment by Kosciany** [comment]
@domenicoblanco  I can confirm that by replacing as you suggested I was able to install the app, thank you :)
