### ISSUE TITLE
Unable to detect TV name

### ISSUE THREAD

**Issue by roblabanca** [Georift/install-jellyfin-tizen#5]
I have an old version of Tizen Jellyfin I installed over 6 months ago, so I attempted to install/update using your docker build which seems way easier :-) 
Its a fairly new Samsung series 8, I have it in developer mode and the ip matches my Macbook Pro
What would cause it to not find the IP address?  They are both connected over wifi to the same access point.
Is there a log I can look at, to help?
----------------
Attempting to connect to Samsung TV at IP address 192.168.1.179
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
error: failed to connect to remote target '192.168.1.179'
Attempting to get the TV name...
We were unable to find the TV name.

**Comment by Georift** [comment]
Hi there, could you double check the IP address for the TV is correct? Best to open your router to see if you can see it listed there.

Also if that is correct, could you try opening this link on your network and pasting the output here:

http://192.168.1.179:8001/api/v2/

**Comment by roblabanca** [comment]
When in developer mode, does the ip address you manually enter (to match the docker host) override the IP address the TV pulled on its own?  Because the Samsung has a different IP in DHCP lease list on the router.

**Comment by Georift** [comment]
Nope, the IP you enter should match your docker host.

The IP you found on the router should be pasted into the command:

```
docker run --rm georift/install-jellyfin-tizen <paste samsung tv router ip here>
```

**Comment by roblabanca** [comment]
That worked perfectly.  Thanks for your support.
One note, I did have to remove the previous version of Jellyfin app that I had install manually myself.
