### ISSUE TITLE
The command doesn't work anymore after updating tizen os

### ISSUE THREAD

**Issue by b-des** [Georift/install-jellyfin-tizen#50]
Hi @Georift,
first of all thanks for your time and the work you have made. 

It's awesome and worked fine for me just before I updated my TV. After I installed Jellyfin using your docker command I noticed the updates for my QN90 and installed it. After a while when the TV was rebooted the installed Jellyfin disappeared, and trying to reinstall it leads to this error:
```
Server is not running. Start it now on port 26099 

Server has started successfully

error: failed to connect to remote target '192.168.1.105'

Attempting to get the TV name...

We were unable to find the TV name.
```

There is the chance that port for development mode has been changed, since I can't see that port 26099 is open using port scanning tool neither native device manager can discover device. 

Do you have idea how it can be checked and maybe fixed? Thanks in advance!

**Comment by InsulT** [comment]
Having the same issue here :S

**Comment by Tunu-de** [comment]
I have the Same Error with my Samsung S90C.

# Platform log view
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin-intros-TrueHD.wgt
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[9]
app_id[AprZAARz4r.Jellyfin] installing[19]
app_id[AprZAARz4r.Jellyfin] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [7995]ms
Failed to install Tizen application.
Total time: 00:00:10.281


And Thank you @InsulT for the tip with the DEV Mode.

**Comment by noobmagnet** [comment]
Having the same issue on the S90c... I wish I hadn't updated now, so annoying

I did factory reset just in case, but I get the same error as the others above

**Comment by andyklimczak** [comment]
Related: https://github.com/jeppevinkel/jellyfin-tizen-builds/issues/55

**Comment by Tunu-de** [comment]
As a Workaround on the Issue #21 is an Documentation from @SayantanRC

> It took me several SEVERAL hours to get it working. But here is a noob friendly guide - including how to setup tizen studio.
https://gist.github.com/SayantanRC/57762c8933f12a81501d8cd3cddb08e4


This worked for me. But it need some time and its not so easy

**Comment by jerojero** [comment]
If getting the right certs cannot be automated it's going to be a nightmare to update the app.

**Comment by sej75** [comment]
> As a Workaround on the Issue #21 is an Documentation from @SayantanRC
> 
> > It took me several SEVERAL hours to get it working. But here is a noob friendly guide - including how to setup tizen studio.
> > https://gist.github.com/SayantanRC/57762c8933f12a81501d8cd3cddb08e4
> 
> This worked for me. But it need some time and its not so easy

Many thanks for this link! It worked perfectly for me. I installed One UI on my Samsung TV and I lost Jellyfin and couldn't put it back! But, thanks to this link I finally managed to put it back!

**Comment by b-des** [comment]
Closing this issue. The working solution can be found here:
https://gist.github.com/SayantanRC/57762c8933f12a81501d8cd3cddb08e4
