### ISSUE TITLE
Issue running Docker command on MacOS

### ISSUE THREAD

**Issue by SunnySkye** [Georift/install-jellyfin-tizen#52]
Hi there,

I think this is an issue with the repo but I could be wrong.
Here's what I am running:
`docker run --rm ghcr.io/georift/install-jellyfin-tizen 10.2.1.6 `

Here is the error in response:
`Unable to find image 'ghcr.io/georift/install-jellyfin-tizen:latest' locally
latest: Pulling from georift/install-jellyfin-tizen
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.`

Any assistance or guidance would be deeply appreciated <3

**Comment by Epgenix** [comment]
It pretty easy to fix this.

Firstly make sure that you have the Experimental "Virtualization Framework" enabled. 
Verify that docker on your M series has qemu installed. You can do this by running: 
`docker run --rm --platform linux/amd64 alpine uname -m`

If it outputs: `x86_64` you're good. If not, reinstall docker.

Then use the "--platform linux/amd64" argument on the original command. This should look something like this: 
`docker run --rm --platform linux/amd64 ghcr.io/georift/install-jellyfin-tizen <samsung tv ip> <build option> <tag url>`

Done.

**Comment by SunnySkye** [comment]
@Epgenix You're a genius!
It installed and is working wonderfully.
Thank you so much for all your amazing work.

**Comment by Georift** [comment]
Thanks for the comment @Epgenix. Yeah unfortunately Tizen doesn't have arm builds #10. This work around should probably be documented somewhere.

**Comment by Epgenix** [comment]
@Georift Should i make a Pull request for the readme?
