### ISSUE TITLE
It just hangs

### ISSUE THREAD

**Issue by andreclemente** [Georift/install-jellyfin-tizen#7]
First of all I would like to thank you for all your work and effort. 

I'm trying to run the docker image but it just hangs. It doesn't do anything and I have to force close the terminal (Ctrl+C doesn't even stop it). Any idea?

```
Attempting to connect to Samsung TV at IP address 192.168.1.242
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 192.168.1.242:26101 ...
failed to connect to 192.168.1.242:26101
Attempting to get the TV name...
Found TV name: UE43BU8505KXXC
Attempting to install jellyfin-tizen-builds version:
https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2023-02-06


```

**Comment by andreclemente** [comment]
For who else encounters this issue, I was able to install the app using this method: https://github.com/babagreensheep/jellyfin-tizen-docker

**Comment by Georift** [comment]
Thanks for the report, could you do me a favor and try running this command on your machine?

`curl -v location: https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/latest`

I suspect something here is getting stuck and we're not seeing any messages.

**Comment by tonybolzan** [comment]
I receive the same error `failed to connect to 192.168.100.14:26101`
The sdb don't see the TV but http://192.168.100.14:8001/api/v2/ respond with valid json
My Model name are `QN55QN85BAGXZD`

**Comment by WarHatch** [comment]
@tonybolzan I had a similar issue. I'd say make sure the TV has the correct PC ip entered. You can try using your pc's public ip.
My issue was that I was on ethernet connection on my pc, but a wifi connection for the TV - I'd entered the pc local network ethernet ip, which the TV did not recognize when the `sdb` command was running. There may also be issues if your devices are connected via different routers.

**Comment by Georift** [comment]
I'm closing this as it seems stale now. If anyone has a similar issue feel free to raise a new issue and mention this one.
