### ISSUE TITLE
Jellyfin App Icon Change

### ISSUE THREAD

**Issue by mjeshurun** [Georift/install-jellyfin-tizen#8]
Hi @Georift ,
Thank you for creating this tool. It helped me re-install the Jellyfin app on my Samsung TV very easily. 
I just have one suggestion (or request). 
Would it be possible to update the app icon to a rectangular shape, similar to all other app's icons on the TV?
I've attached an alternative app icon with the right proportions. 
Hope you can assist with this 🙏

![icon](https://user-images.githubusercontent.com/10453588/221441873-4e3f9de5-4ed9-415a-91de-ff0ac55932e5.png)

**Comment by ilteoood** [comment]
This should be discussed here: https://github.com/jellyfin/jellyfin-tizen/pull/176

**Comment by Georift** [comment]
Yep, thanks for the linking :)
